"""
Function Executor for FunctionGemma Integration

This module provides the FunctionExecutor class that executes function calls
generated by the FunctionGemma planner service. It handles parameter validation,
error handling, execution order preservation, and parallel execution support.

Key Features:
- Execute individual function calls with parameter validation
- Execute sequences of function calls in order
- Error handling with severity-based continue/abort logic
- Support for parallel execution of independent operations
- Overall status reporting for multi-step execution

Requirements Validated:
- 10.5: Pre-execution parameter validation
- 12.2: Execution order preservation
- 12.3: Error severity handling
- 12.4: Parallel execution support
- 12.5: Overall status reporting
"""

import logging
import time
from typing import List, Dict, Optional, Callable, Set
from dataclasses import dataclass
from concurrent.futures import ThreadPoolExecutor, as_completed
import traceback
import asyncio
from functools import wraps

# Import data models from functiongemma_service
from functiongemma_service import FunctionCall, ExecutionResult

# Import monitoring
from monitoring import get_monitoring_dashboard

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


@dataclass
class MultiStepExecutionResult:
    """Result of multi-step task execution."""
    overall_success: bool
    step_results: List[ExecutionResult]
    total_steps: int
    successful_steps: int
    failed_steps: int
    
    def to_dict(self) -> dict:
        """Convert to dictionary."""
        return {
            "overall_success": self.overall_success,
            "step_results": [r.to_dict() for r in self.step_results],
            "total_steps": self.total_steps,
            "successful_steps": self.successful_steps,
            "failed_steps": self.failed_steps
        }


class ErrorSeverity:
    """Error severity levels for execution control."""
    CRITICAL = "critical"  # Abort execution
    NON_CRITICAL = "non_critical"  # Continue execution


class FunctionExecutor:
    """
    Executor for function calls generated by FunctionGemma.
    
    This class handles the execution of function calls with proper error handling,
    parameter validation, and support for both sequential and parallel execution.
    
    Attributes:
        function_registry: Registry of available functions
        abort_on_error: Whether to abort on first error (default: False)
        max_parallel_workers: Maximum workers for parallel execution (default: 4)
    """
    
    # Critical error patterns that should abort execution
    CRITICAL_ERROR_PATTERNS = [
        "permission denied",
        "access denied",
        "out of memory",
        "disk full",
        "system error",
        "fatal error",
        "registry corruption",
        "resource exhaustion"
    ]
    
    def __init__(
        self,
        function_registry,
        abort_on_error: bool = False,
        max_parallel_workers: int = 4,
        enable_profiling: bool = False
    ):
        """
        Initialize the function executor.
        
        Args:
            function_registry: Registry of available functions
            abort_on_error: Whether to abort on first error (default: False)
            max_parallel_workers: Maximum workers for parallel execution (default: 4)
            enable_profiling: Whether to enable execution profiling (default: False)
        """
        self.function_registry = function_registry
        self.abort_on_error = abort_on_error
        self.max_parallel_workers = max_parallel_workers
        self.enable_profiling = enable_profiling
        
        # Profiling data
        self._execution_times = {}  # function_name -> list of execution times
        self._execution_counts = {}  # function_name -> count
        
        logger.info(
            f"FunctionExecutor initialized "
            f"(abort_on_error={abort_on_error}, "
            f"max_parallel_workers={max_parallel_workers}, "
            f"profiling={enable_profiling})"
        )
    
    def execute_function_call(
        self,
        function_call: FunctionCall,
        validate_params: bool = True
    ) -> ExecutionResult:
        """
        Execute a single function call with parameter validation.
        
        This method validates parameters against the function schema before execution
        and handles all errors gracefully, returning an ExecutionResult.
        Includes optional profiling for performance optimization.
        
        Args:
            function_call: FunctionCall object to execute
            validate_params: Whether to validate parameters (default: True)
        
        Returns:
            ExecutionResult with success status and result/error
        
        Validates: Requirements 10.5 (Pre-execution parameter validation)
        """
        function_name = function_call.name
        arguments = function_call.arguments
        
        logger.info(f"Executing function: {function_name}")
        logger.debug(f"Arguments: {arguments}")
        
        # Start monitoring
        dashboard = get_monitoring_dashboard()
        operation_id = dashboard.performance_monitor.start_operation(
            operation_type="function_call",
            function_name=function_name,
            parameters=arguments
        )
        
        # Start profiling if enabled
        start_time = time.perf_counter() if self.enable_profiling else None
        
        try:
            # Step 1: Check if function exists in registry
            function_impl = self.function_registry.get_function(function_name)
            
            if function_impl is None:
                error_msg = f"Function '{function_name}' not found in registry"
                logger.error(error_msg)
                
                # Log error to monitoring
                dashboard.error_tracker.log_error(
                    error_type="function_not_found",
                    error_message=error_msg,
                    function_name=function_name,
                    parameters=arguments
                )
                dashboard.performance_monitor.complete_operation(
                    operation_id, success=False, error_message=error_msg
                )
                
                return ExecutionResult(
                    success=False,
                    function_name=function_name,
                    result={},
                    error_message=error_msg
                )
            
            # Step 2: Check if function is a placeholder
            if self.function_registry.is_placeholder(function_name):
                error_msg = f"Function '{function_name}' is a placeholder and not yet implemented"
                logger.warning(error_msg)
                
                # Log error to monitoring
                dashboard.error_tracker.log_error(
                    error_type="placeholder_function",
                    error_message=error_msg,
                    function_name=function_name,
                    parameters=arguments
                )
                dashboard.performance_monitor.complete_operation(
                    operation_id, success=False, error_message=error_msg
                )
                
                return ExecutionResult(
                    success=False,
                    function_name=function_name,
                    result={},
                    error_message=error_msg
                )
            
            # Step 3: Validate parameters against schema (Requirement 10.5)
            if validate_params:
                is_valid, validation_error = self.function_registry.validate_parameters(
                    function_name,
                    arguments
                )
                
                if not is_valid:
                    logger.error(f"Parameter validation failed: {validation_error}")
                    
                    # Log error to monitoring
                    dashboard.error_tracker.log_error(
                        error_type="parameter_validation",
                        error_message=validation_error,
                        function_name=function_name,
                        parameters=arguments
                    )
                    dashboard.performance_monitor.complete_operation(
                        operation_id, success=False, error_message=validation_error
                    )
                    
                    return ExecutionResult(
                        success=False,
                        function_name=function_name,
                        result={},
                        error_message=f"Invalid parameters: {validation_error}"
                    )
            
            # Step 4: Execute the function
            logger.debug(f"Calling {function_name} with validated parameters")
            result = function_impl(**arguments)
            
            # Step 5: Check result format
            if not isinstance(result, dict):
                logger.warning(
                    f"Function '{function_name}' returned non-dict result. "
                    f"Wrapping in dict."
                )
                result = {"value": result}
            
            # Step 6: Determine success from result
            success = result.get("success", True)
            
            if success:
                logger.info(f"✓ Function '{function_name}' executed successfully")
            else:
                logger.warning(
                    f"Function '{function_name}' returned success=False: "
                    f"{result.get('message', 'No message')}"
                )
            
            # Record profiling data
            if self.enable_profiling and start_time is not None:
                execution_time = time.perf_counter() - start_time
                self._record_execution_time(function_name, execution_time)
            
            # Complete monitoring
            dashboard.performance_monitor.complete_operation(
                operation_id,
                success=success,
                error_message=result.get("message") if not success else None,
                result=result
            )
            
            # Log error if function returned failure
            if not success:
                dashboard.error_tracker.log_error(
                    error_type="function_execution",
                    error_message=result.get("message", "Unknown error"),
                    function_name=function_name,
                    parameters=arguments,
                    context={"result": result}
                )
            
            return ExecutionResult(
                success=success,
                function_name=function_name,
                result=result,
                error_message=result.get("message") if not success else None
            )
            
        except TypeError as e:
            # Handle parameter type errors
            error_msg = f"Type error calling '{function_name}': {str(e)}"
            logger.error(error_msg)
            logger.debug(traceback.format_exc())
            
            # Log error to monitoring
            dashboard.error_tracker.log_error(
                error_type="type_error",
                error_message=error_msg,
                function_name=function_name,
                parameters=arguments,
                stack_trace=traceback.format_exc()
            )
            
            # Record profiling data for errors too
            if self.enable_profiling and start_time is not None:
                execution_time = time.perf_counter() - start_time
                self._record_execution_time(function_name, execution_time)
            
            # Complete monitoring
            dashboard.performance_monitor.complete_operation(
                operation_id, success=False, error_message=error_msg
            )
            
            return ExecutionResult(
                success=False,
                function_name=function_name,
                result={},
                error_message=error_msg
            )
            
        except Exception as e:
            # Handle all other execution errors
            error_msg = f"Error executing '{function_name}': {str(e)}"
            logger.error(error_msg)
            logger.debug(traceback.format_exc())
            
            # Log error to monitoring
            dashboard.error_tracker.log_error(
                error_type="execution_error",
                error_message=error_msg,
                function_name=function_name,
                parameters=arguments,
                stack_trace=traceback.format_exc()
            )
            
            # Record profiling data for errors too
            if self.enable_profiling and start_time is not None:
                execution_time = time.perf_counter() - start_time
                self._record_execution_time(function_name, execution_time)
            
            # Complete monitoring
            dashboard.performance_monitor.complete_operation(
                operation_id, success=False, error_message=error_msg
            )
            
            return ExecutionResult(
                success=False,
                function_name=function_name,
                result={},
                error_message=error_msg
            )
    
    def execute_sequence(
        self,
        function_calls: List[FunctionCall],
        parallel: bool = False
    ) -> MultiStepExecutionResult:
        """
        Execute a sequence of function calls with order preservation.
        
        This method executes function calls in the exact order specified (sequential mode)
        or in parallel (parallel mode) for independent operations. It handles errors
        based on severity and generates an overall status report.
        
        Args:
            function_calls: List of FunctionCall objects to execute
            parallel: Whether to execute in parallel (default: False)
        
        Returns:
            MultiStepExecutionResult with overall status and individual results
        
        Validates:
            - Requirements 12.2: Execution order preservation (sequential mode)
            - Requirements 12.3: Error severity handling
            - Requirements 12.4: Parallel execution support (parallel mode)
            - Requirements 12.5: Overall status reporting
        """
        if not function_calls:
            logger.warning("No function calls to execute")
            return MultiStepExecutionResult(
                overall_success=True,
                step_results=[],
                total_steps=0,
                successful_steps=0,
                failed_steps=0
            )
        
        total_steps = len(function_calls)
        logger.info(
            f"Executing {total_steps} function call(s) "
            f"(mode: {'parallel' if parallel else 'sequential'})"
        )
        
        # Execute based on mode
        if parallel:
            step_results = self._execute_parallel(function_calls)
        else:
            step_results = self._execute_sequential(function_calls)
        
        # Calculate overall status (Requirement 12.5)
        successful_steps = sum(1 for r in step_results if r.success)
        failed_steps = len(step_results) - successful_steps
        overall_success = failed_steps == 0
        
        logger.info(
            f"Execution complete: {successful_steps}/{total_steps} successful, "
            f"{failed_steps} failed"
        )
        
        return MultiStepExecutionResult(
            overall_success=overall_success,
            step_results=step_results,
            total_steps=total_steps,
            successful_steps=successful_steps,
            failed_steps=failed_steps
        )
    
    def _execute_sequential(
        self,
        function_calls: List[FunctionCall]
    ) -> List[ExecutionResult]:
        """
        Execute function calls sequentially in order.
        
        Preserves execution order and handles errors based on severity.
        
        Args:
            function_calls: List of FunctionCall objects
        
        Returns:
            List of ExecutionResult objects in order
        
        Validates: Requirements 12.2 (Execution order preservation)
        """
        results = []
        
        for i, function_call in enumerate(function_calls, 1):
            logger.info(f"Step {i}/{len(function_calls)}: {function_call.name}")
            
            # Execute the function call
            result = self.execute_function_call(function_call)
            results.append(result)
            
            # Check if we should abort on error (Requirement 12.3)
            if not result.success:
                severity = self._determine_error_severity(result.error_message)
                
                if severity == ErrorSeverity.CRITICAL or self.abort_on_error:
                    logger.error(
                        f"Critical error or abort_on_error=True. "
                        f"Aborting remaining {len(function_calls) - i} step(s)."
                    )
                    break
                else:
                    logger.warning(
                        f"Non-critical error. Continuing with remaining steps."
                    )
        
        return results
    
    def _execute_parallel(
        self,
        function_calls: List[FunctionCall]
    ) -> List[ExecutionResult]:
        """
        Execute function calls in parallel.
        
        Uses ThreadPoolExecutor to execute independent operations concurrently.
        Results are returned in the original order of function_calls.
        
        Args:
            function_calls: List of FunctionCall objects
        
        Returns:
            List of ExecutionResult objects in original order
        
        Validates: Requirements 12.4 (Parallel execution support)
        """
        results = [None] * len(function_calls)
        
        with ThreadPoolExecutor(max_workers=self.max_parallel_workers) as executor:
            # Submit all function calls
            future_to_index = {
                executor.submit(self.execute_function_call, fc): i
                for i, fc in enumerate(function_calls)
            }
            
            # Collect results as they complete
            for future in as_completed(future_to_index):
                index = future_to_index[future]
                
                try:
                    result = future.result()
                    results[index] = result
                    
                    if result.success:
                        logger.info(
                            f"✓ Parallel task {index + 1} completed: "
                            f"{result.function_name}"
                        )
                    else:
                        logger.warning(
                            f"✗ Parallel task {index + 1} failed: "
                            f"{result.function_name} - {result.error_message}"
                        )
                        
                except Exception as e:
                    # Handle unexpected errors in parallel execution
                    logger.error(f"Parallel task {index + 1} raised exception: {e}")
                    results[index] = ExecutionResult(
                        success=False,
                        function_name=function_calls[index].name,
                        result={},
                        error_message=f"Parallel execution error: {str(e)}"
                    )
        
        return results
    
    def _determine_error_severity(self, error_message: Optional[str]) -> str:
        """
        Determine error severity based on error message.
        
        Checks error message against critical error patterns to decide
        whether execution should abort or continue.
        
        Args:
            error_message: Error message to analyze
        
        Returns:
            ErrorSeverity.CRITICAL or ErrorSeverity.NON_CRITICAL
        
        Validates: Requirements 12.3 (Error severity handling)
        """
        if error_message is None:
            return ErrorSeverity.NON_CRITICAL
        
        error_lower = error_message.lower()
        
        # Check for critical error patterns
        for pattern in self.CRITICAL_ERROR_PATTERNS:
            if pattern in error_lower:
                logger.debug(f"Critical error pattern detected: '{pattern}'")
                return ErrorSeverity.CRITICAL
        
        return ErrorSeverity.NON_CRITICAL
    
    def can_execute_parallel(
        self,
        function_calls: List[FunctionCall]
    ) -> bool:
        """
        Determine if function calls can be executed in parallel.
        
        Analyzes function calls to detect dependencies and shared resources.
        Returns True only if all operations are independent.
        
        Args:
            function_calls: List of FunctionCall objects
        
        Returns:
            True if parallel execution is safe, False otherwise
        
        Note: This is a conservative implementation that checks for obvious
        dependencies. More sophisticated dependency analysis could be added.
        """
        if len(function_calls) <= 1:
            return False
        
        # Track resources accessed by each function
        file_operations = {"delete_file", "rename_file", "copy_file", "move_file", "open_file"}
        folder_operations = {"create_folder", "delete_folder", "open_folder", "list_folder"}
        window_operations = {"activate_window", "close_window", "minimize_window", "maximize_window"}
        
        # Track accessed resources
        accessed_files: Set[str] = set()
        accessed_folders: Set[str] = set()
        accessed_windows: Set[str] = set()
        
        for fc in function_calls:
            # Check for file operations
            if fc.name in file_operations:
                path = fc.arguments.get("path") or fc.arguments.get("source") or fc.arguments.get("old_path")
                if path:
                    if path in accessed_files:
                        logger.debug(f"Dependency detected: file '{path}' accessed multiple times")
                        return False
                    accessed_files.add(path)
            
            # Check for folder operations
            if fc.name in folder_operations:
                path = fc.arguments.get("path")
                if path:
                    if path in accessed_folders:
                        logger.debug(f"Dependency detected: folder '{path}' accessed multiple times")
                        return False
                    accessed_folders.add(path)
            
            # Check for window operations
            if fc.name in window_operations:
                identifier = fc.arguments.get("identifier")
                if identifier:
                    if identifier in accessed_windows:
                        logger.debug(f"Dependency detected: window '{identifier}' accessed multiple times")
                        return False
                    accessed_windows.add(identifier)
            
            # Keyboard and mouse operations should not be parallelized
            # (they need to happen in sequence for UI interactions)
            if fc.name.startswith("type_") or fc.name.startswith("press_") or \
               fc.name in {"click", "double_click", "right_click", "move_mouse", "drag"}:
                logger.debug(f"UI operation detected: {fc.name} - cannot parallelize")
                return False
        
        logger.debug("No dependencies detected - parallel execution is safe")
        return True
    
    def set_abort_on_error(self, abort: bool):
        """
        Set whether to abort on first error.
        
        Args:
            abort: True to abort on first error, False to continue
        """
        self.abort_on_error = abort
        logger.info(f"abort_on_error set to {abort}")
    
    def set_max_parallel_workers(self, workers: int):
        """
        Set maximum parallel workers.
        
        Args:
            workers: Maximum number of parallel workers (must be > 0)
        
        Raises:
            ValueError: If workers <= 0
        """
        if workers <= 0:
            raise ValueError("max_parallel_workers must be greater than 0")
        
        self.max_parallel_workers = workers
        logger.info(f"max_parallel_workers set to {workers}")
    
    def _record_execution_time(self, function_name: str, execution_time: float):
        """
        Record execution time for profiling.
        
        Args:
            function_name: Name of the function
            execution_time: Execution time in seconds
        """
        if function_name not in self._execution_times:
            self._execution_times[function_name] = []
            self._execution_counts[function_name] = 0
        
        self._execution_times[function_name].append(execution_time)
        self._execution_counts[function_name] += 1
    
    def get_profiling_stats(self) -> Dict[str, Dict[str, float]]:
        """
        Get profiling statistics for all executed functions.
        
        Returns:
            Dict mapping function names to stats:
            {
                "function_name": {
                    "count": int,
                    "total_time": float,
                    "avg_time": float,
                    "min_time": float,
                    "max_time": float
                }
            }
        """
        stats = {}
        
        for function_name, times in self._execution_times.items():
            if times:
                stats[function_name] = {
                    "count": self._execution_counts[function_name],
                    "total_time": sum(times),
                    "avg_time": sum(times) / len(times),
                    "min_time": min(times),
                    "max_time": max(times)
                }
        
        return stats
    
    def print_profiling_report(self):
        """Print a formatted profiling report."""
        stats = self.get_profiling_stats()
        
        if not stats:
            logger.info("No profiling data available")
            return
        
        logger.info("=" * 80)
        logger.info("FUNCTION EXECUTION PROFILING REPORT")
        logger.info("=" * 80)
        
        # Sort by total time (descending)
        sorted_stats = sorted(
            stats.items(),
            key=lambda x: x[1]["total_time"],
            reverse=True
        )
        
        for function_name, data in sorted_stats:
            logger.info(f"\n{function_name}:")
            logger.info(f"  Executions: {data['count']}")
            logger.info(f"  Total time: {data['total_time']:.4f}s")
            logger.info(f"  Avg time:   {data['avg_time']:.4f}s")
            logger.info(f"  Min time:   {data['min_time']:.4f}s")
            logger.info(f"  Max time:   {data['max_time']:.4f}s")
        
        logger.info("=" * 80)
    
    def reset_profiling_data(self):
        """Reset all profiling data."""
        self._execution_times.clear()
        self._execution_counts.clear()
        logger.info("Profiling data reset")
    
    def get_slow_operations(self, threshold_seconds: float = 1.0) -> List[str]:
        """
        Get list of operations that exceed the time threshold.
        
        Args:
            threshold_seconds: Time threshold in seconds (default: 1.0)
        
        Returns:
            List of function names with avg execution time > threshold
        """
        stats = self.get_profiling_stats()
        slow_ops = []
        
        for function_name, data in stats.items():
            if data["avg_time"] > threshold_seconds:
                slow_ops.append(function_name)
        
        return slow_ops
    
    async def execute_function_call_async(
        self,
        function_call: FunctionCall,
        validate_params: bool = True
    ) -> ExecutionResult:
        """
        Execute a function call asynchronously.
        
        This is a wrapper around execute_function_call that runs it in
        an executor to avoid blocking the event loop.
        
        Args:
            function_call: FunctionCall object to execute
            validate_params: Whether to validate parameters
        
        Returns:
            ExecutionResult with success status and result/error
        """
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(
            None,
            self.execute_function_call,
            function_call,
            validate_params
        )
    
    async def execute_sequence_async(
        self,
        function_calls: List[FunctionCall],
        parallel: bool = False
    ) -> MultiStepExecutionResult:
        """
        Execute a sequence of function calls asynchronously.
        
        Args:
            function_calls: List of FunctionCall objects to execute
            parallel: Whether to execute in parallel (default: False)
        
        Returns:
            MultiStepExecutionResult with overall status and individual results
        """
        if not function_calls:
            return MultiStepExecutionResult(
                overall_success=True,
                step_results=[],
                total_steps=0,
                successful_steps=0,
                failed_steps=0
            )
        
        if parallel:
            # Execute all calls concurrently
            tasks = [
                self.execute_function_call_async(fc)
                for fc in function_calls
            ]
            step_results = await asyncio.gather(*tasks)
        else:
            # Execute sequentially
            step_results = []
            for fc in function_calls:
                result = await self.execute_function_call_async(fc)
                step_results.append(result)
                
                # Check if we should abort
                if not result.success:
                    severity = self._determine_error_severity(result.error_message)
                    if severity == ErrorSeverity.CRITICAL or self.abort_on_error:
                        break
        
        # Calculate overall status
        successful_steps = sum(1 for r in step_results if r.success)
        failed_steps = len(step_results) - successful_steps
        overall_success = failed_steps == 0
        
        return MultiStepExecutionResult(
            overall_success=overall_success,
            step_results=step_results,
            total_steps=len(function_calls),
            successful_steps=successful_steps,
            failed_steps=failed_steps
        )
